using MiningManager.ViewModel;

namespace MiningManager.View
{
    /// <summary>
    /// Logique d'interaction pour ItemManagerView.xaml
    /// </summary>
    public partial class EntityMgrView : ValidationErrorView
    {
        public EntityMgrView()
        {
            InitializeComponent();
        }

        private void DgGeneric_AutoGeneratedColumns(object sender, System.EventArgs e)
        {
            ((IDatagridGeneratingColumns)DataContext).DataGridColumnManagment(dgGeneric.Columns);
        }
    }
}
